2019-10-02 17:24:06.550 [error] <0.24118.1> gen_fsm <0.24118.1> in state connecting terminated with reason: {error,{unknown_target_type,test_name_locator}}
2019-10-02 17:24:06.550 [error] <0.24118.1> CRASH REPORT Process <0.24118.1> with 0 neighbours exited with reason: {error,{unknown_target_type,test_name_locator}} in gen_fsm:terminate/7 line 622
2019-10-02 17:24:06.550 [error] <0.23953.1> Supervisor riak_core_cluster_conn_sup had child {test_name_locator,{"127.0.0.1",4097}} started with riak_core_cluster_conn:start_link({test_name_locator,{"127.0.0.1",4097}}) at <0.24118.1> exit with reason {error,{unknown_target_type,test_name_locator}} in context child_terminated
2019-10-02 17:24:06.550 [error] <0.24119.1> gen_fsm <0.24119.1> in state connecting terminated with reason: {error,{unknown_target_type,test_name_locator}}
2019-10-02 17:24:06.551 [error] <0.24119.1> CRASH REPORT Process <0.24119.1> with 0 neighbours exited with reason: {error,{unknown_target_type,test_name_locator}} in gen_fsm:terminate/7 line 622
2019-10-02 17:24:06.551 [error] <0.23953.1> Supervisor riak_core_cluster_conn_sup had child {test_name_locator,{"127.0.0.1",4097}} started with riak_core_cluster_conn:start_link({test_name_locator,{"127.0.0.1",4097}}) at <0.24119.1> exit with reason {error,{unknown_target_type,test_name_locator}} in context child_terminated
2019-10-02 17:24:06.551 [error] <0.24120.1> gen_fsm <0.24120.1> in state connecting terminated with reason: {error,{unknown_target_type,test_name_locator}}
2019-10-02 17:24:06.551 [error] <0.24120.1> CRASH REPORT Process <0.24120.1> with 0 neighbours exited with reason: {error,{unknown_target_type,test_name_locator}} in gen_fsm:terminate/7 line 622
2019-10-02 17:24:06.551 [error] <0.23953.1> Supervisor riak_core_cluster_conn_sup had child {test_name_locator,{"127.0.0.1",4097}} started with riak_core_cluster_conn:start_link({test_name_locator,{"127.0.0.1",4097}}) at <0.24120.1> exit with reason {error,{unknown_target_type,test_name_locator}} in context child_terminated
2019-10-02 17:24:06.551 [error] <0.24121.1> gen_fsm <0.24121.1> in state connecting terminated with reason: {error,{unknown_target_type,test_name_locator}}
2019-10-02 17:24:06.551 [error] <0.24121.1> CRASH REPORT Process <0.24121.1> with 0 neighbours exited with reason: {error,{unknown_target_type,test_name_locator}} in gen_fsm:terminate/7 line 622
2019-10-02 17:24:06.551 [error] <0.23953.1> Supervisor riak_core_cluster_conn_sup had child {test_name_locator,{"127.0.0.1",4097}} started with riak_core_cluster_conn:start_link({test_name_locator,{"127.0.0.1",4097}}) at <0.24121.1> exit with reason {error,{unknown_target_type,test_name_locator}} in context child_terminated
2019-10-02 17:24:06.551 [error] <0.24122.1> gen_fsm <0.24122.1> in state connecting terminated with reason: {error,{unknown_target_type,test_name_locator}}
2019-10-02 17:24:06.551 [error] <0.24122.1> CRASH REPORT Process <0.24122.1> with 0 neighbours exited with reason: {error,{unknown_target_type,test_name_locator}} in gen_fsm:terminate/7 line 622
2019-10-02 17:24:06.551 [error] <0.23953.1> Supervisor riak_core_cluster_conn_sup had child {test_name_locator,{"127.0.0.1",4097}} started with riak_core_cluster_conn:start_link({test_name_locator,{"127.0.0.1",4097}}) at <0.24122.1> exit with reason {error,{unknown_target_type,test_name_locator}} in context child_terminated
2019-10-02 17:24:06.551 [error] <0.24123.1> gen_fsm <0.24123.1> in state connecting terminated with reason: {error,{unknown_target_type,test_name_locator}}
2019-10-02 17:24:06.552 [error] <0.24123.1> CRASH REPORT Process <0.24123.1> with 0 neighbours exited with reason: {error,{unknown_target_type,test_name_locator}} in gen_fsm:terminate/7 line 622
2019-10-02 17:24:06.552 [error] <0.23953.1> Supervisor riak_core_cluster_conn_sup had child {test_name_locator,{"127.0.0.1",4097}} started with riak_core_cluster_conn:start_link({test_name_locator,{"127.0.0.1",4097}}) at <0.24123.1> exit with reason {error,{unknown_target_type,test_name_locator}} in context child_terminated
2019-10-02 17:24:06.552 [error] <0.24124.1> gen_fsm <0.24124.1> in state connecting terminated with reason: {error,{unknown_target_type,test_name_locator}}
2019-10-02 17:24:06.552 [error] <0.24124.1> CRASH REPORT Process <0.24124.1> with 0 neighbours exited with reason: {error,{unknown_target_type,test_name_locator}} in gen_fsm:terminate/7 line 622
2019-10-02 17:24:06.552 [error] <0.23953.1> Supervisor riak_core_cluster_conn_sup had child {test_name_locator,{"127.0.0.1",4097}} started with riak_core_cluster_conn:start_link({test_name_locator,{"127.0.0.1",4097}}) at <0.24124.1> exit with reason {error,{unknown_target_type,test_name_locator}} in context child_terminated
2019-10-02 17:24:06.552 [error] <0.24125.1> gen_fsm <0.24125.1> in state connecting terminated with reason: {error,{unknown_target_type,test_name_locator}}
2019-10-02 17:24:06.552 [error] <0.24125.1> CRASH REPORT Process <0.24125.1> with 0 neighbours exited with reason: {error,{unknown_target_type,test_name_locator}} in gen_fsm:terminate/7 line 622
2019-10-02 17:24:06.552 [error] <0.23953.1> Supervisor riak_core_cluster_conn_sup had child {test_name_locator,{"127.0.0.1",4097}} started with riak_core_cluster_conn:start_link({test_name_locator,{"127.0.0.1",4097}}) at <0.24125.1> exit with reason {error,{unknown_target_type,test_name_locator}} in context child_terminated
2019-10-02 17:24:06.552 [error] <0.24126.1> gen_fsm <0.24126.1> in state connecting terminated with reason: {error,{unknown_target_type,test_name_locator}}
2019-10-02 17:24:06.552 [error] <0.24126.1> CRASH REPORT Process <0.24126.1> with 0 neighbours exited with reason: {error,{unknown_target_type,test_name_locator}} in gen_fsm:terminate/7 line 622
2019-10-02 17:24:06.552 [error] <0.23953.1> Supervisor riak_core_cluster_conn_sup had child {test_name_locator,{"127.0.0.1",4097}} started with riak_core_cluster_conn:start_link({test_name_locator,{"127.0.0.1",4097}}) at <0.24126.1> exit with reason {error,{unknown_target_type,test_name_locator}} in context child_terminated
2019-10-02 17:24:06.552 [error] <0.24127.1> gen_fsm <0.24127.1> in state connecting terminated with reason: {error,{unknown_target_type,test_name_locator}}
2019-10-02 17:24:06.552 [error] <0.24127.1> CRASH REPORT Process <0.24127.1> with 0 neighbours exited with reason: {error,{unknown_target_type,test_name_locator}} in gen_fsm:terminate/7 line 622
2019-10-02 17:24:06.552 [error] <0.23953.1> Supervisor riak_core_cluster_conn_sup had child {test_name_locator,{"127.0.0.1",4097}} started with riak_core_cluster_conn:start_link({test_name_locator,{"127.0.0.1",4097}}) at <0.24127.1> exit with reason {error,{unknown_target_type,test_name_locator}} in context child_terminated
2019-10-02 17:24:06.553 [error] <0.24128.1> gen_fsm <0.24128.1> in state connecting terminated with reason: {error,{unknown_target_type,test_name_locator}}
2019-10-02 17:24:06.553 [error] <0.24128.1> CRASH REPORT Process <0.24128.1> with 0 neighbours exited with reason: {error,{unknown_target_type,test_name_locator}} in gen_fsm:terminate/7 line 622
2019-10-02 17:24:06.553 [error] <0.23953.1> Supervisor riak_core_cluster_conn_sup had child {test_name_locator,{"127.0.0.1",4097}} started with riak_core_cluster_conn:start_link({test_name_locator,{"127.0.0.1",4097}}) at <0.24128.1> exit with reason {error,{unknown_target_type,test_name_locator}} in context child_terminated
2019-10-02 17:24:06.553 [error] <0.23953.1> Supervisor riak_core_cluster_conn_sup had child {test_name_locator,{"127.0.0.1",4097}} started with riak_core_cluster_conn:start_link({test_name_locator,{"127.0.0.1",4097}}) at <0.24128.1> exit with reason reached_max_restart_intensity in context shutdown
2019-10-02 17:27:04.635 [error] <0.25068.1> gen_fsm <0.25068.1> in state connecting terminated with reason: {error,{unknown_target_type,test_name_locator}}
2019-10-02 17:27:04.635 [error] <0.25068.1> CRASH REPORT Process <0.25068.1> with 0 neighbours exited with reason: {error,{unknown_target_type,test_name_locator}} in gen_fsm:terminate/7 line 622
2019-10-02 17:27:04.635 [error] <0.24906.1> Supervisor riak_core_cluster_conn_sup had child {test_name_locator,{"127.0.0.1",4097}} started with riak_core_cluster_conn:start_link({test_name_locator,{"127.0.0.1",4097}}) at <0.25068.1> exit with reason {error,{unknown_target_type,test_name_locator}} in context child_terminated
2019-10-02 17:27:04.636 [error] <0.25069.1> gen_fsm <0.25069.1> in state connecting terminated with reason: {error,{unknown_target_type,test_name_locator}}
2019-10-02 17:27:04.636 [error] <0.25069.1> CRASH REPORT Process <0.25069.1> with 0 neighbours exited with reason: {error,{unknown_target_type,test_name_locator}} in gen_fsm:terminate/7 line 622
2019-10-02 17:27:04.636 [error] <0.24906.1> Supervisor riak_core_cluster_conn_sup had child {test_name_locator,{"127.0.0.1",4097}} started with riak_core_cluster_conn:start_link({test_name_locator,{"127.0.0.1",4097}}) at <0.25069.1> exit with reason {error,{unknown_target_type,test_name_locator}} in context child_terminated
2019-10-02 17:27:04.636 [error] <0.25070.1> gen_fsm <0.25070.1> in state connecting terminated with reason: {error,{unknown_target_type,test_name_locator}}
2019-10-02 17:27:04.636 [error] <0.25070.1> CRASH REPORT Process <0.25070.1> with 0 neighbours exited with reason: {error,{unknown_target_type,test_name_locator}} in gen_fsm:terminate/7 line 622
2019-10-02 17:27:04.636 [error] <0.24906.1> Supervisor riak_core_cluster_conn_sup had child {test_name_locator,{"127.0.0.1",4097}} started with riak_core_cluster_conn:start_link({test_name_locator,{"127.0.0.1",4097}}) at <0.25070.1> exit with reason {error,{unknown_target_type,test_name_locator}} in context child_terminated
2019-10-02 17:27:04.636 [error] <0.25071.1> gen_fsm <0.25071.1> in state connecting terminated with reason: {error,{unknown_target_type,test_name_locator}}
2019-10-02 17:27:04.636 [error] <0.25071.1> CRASH REPORT Process <0.25071.1> with 0 neighbours exited with reason: {error,{unknown_target_type,test_name_locator}} in gen_fsm:terminate/7 line 622
2019-10-02 17:27:04.637 [error] <0.24906.1> Supervisor riak_core_cluster_conn_sup had child {test_name_locator,{"127.0.0.1",4097}} started with riak_core_cluster_conn:start_link({test_name_locator,{"127.0.0.1",4097}}) at <0.25071.1> exit with reason {error,{unknown_target_type,test_name_locator}} in context child_terminated
2019-10-02 17:27:04.637 [error] <0.25072.1> gen_fsm <0.25072.1> in state connecting terminated with reason: {error,{unknown_target_type,test_name_locator}}
2019-10-02 17:27:04.637 [error] <0.25072.1> CRASH REPORT Process <0.25072.1> with 0 neighbours exited with reason: {error,{unknown_target_type,test_name_locator}} in gen_fsm:terminate/7 line 622
2019-10-02 17:27:04.637 [error] <0.24906.1> Supervisor riak_core_cluster_conn_sup had child {test_name_locator,{"127.0.0.1",4097}} started with riak_core_cluster_conn:start_link({test_name_locator,{"127.0.0.1",4097}}) at <0.25072.1> exit with reason {error,{unknown_target_type,test_name_locator}} in context child_terminated
2019-10-02 17:27:04.637 [error] <0.25073.1> gen_fsm <0.25073.1> in state connecting terminated with reason: {error,{unknown_target_type,test_name_locator}}
2019-10-02 17:27:04.637 [error] <0.25073.1> CRASH REPORT Process <0.25073.1> with 0 neighbours exited with reason: {error,{unknown_target_type,test_name_locator}} in gen_fsm:terminate/7 line 622
2019-10-02 17:27:04.638 [error] <0.24906.1> Supervisor riak_core_cluster_conn_sup had child {test_name_locator,{"127.0.0.1",4097}} started with riak_core_cluster_conn:start_link({test_name_locator,{"127.0.0.1",4097}}) at <0.25073.1> exit with reason {error,{unknown_target_type,test_name_locator}} in context child_terminated
2019-10-02 17:27:04.638 [error] <0.25074.1> gen_fsm <0.25074.1> in state connecting terminated with reason: {error,{unknown_target_type,test_name_locator}}
2019-10-02 17:27:04.638 [error] <0.25074.1> CRASH REPORT Process <0.25074.1> with 0 neighbours exited with reason: {error,{unknown_target_type,test_name_locator}} in gen_fsm:terminate/7 line 622
2019-10-02 17:27:04.638 [error] <0.24906.1> Supervisor riak_core_cluster_conn_sup had child {test_name_locator,{"127.0.0.1",4097}} started with riak_core_cluster_conn:start_link({test_name_locator,{"127.0.0.1",4097}}) at <0.25074.1> exit with reason {error,{unknown_target_type,test_name_locator}} in context child_terminated
2019-10-02 17:27:04.638 [error] <0.25075.1> gen_fsm <0.25075.1> in state connecting terminated with reason: {error,{unknown_target_type,test_name_locator}}
2019-10-02 17:27:04.638 [error] <0.25075.1> CRASH REPORT Process <0.25075.1> with 0 neighbours exited with reason: {error,{unknown_target_type,test_name_locator}} in gen_fsm:terminate/7 line 622
2019-10-02 17:27:04.638 [error] <0.24906.1> Supervisor riak_core_cluster_conn_sup had child {test_name_locator,{"127.0.0.1",4097}} started with riak_core_cluster_conn:start_link({test_name_locator,{"127.0.0.1",4097}}) at <0.25075.1> exit with reason {error,{unknown_target_type,test_name_locator}} in context child_terminated
2019-10-02 17:27:04.638 [error] <0.25076.1> gen_fsm <0.25076.1> in state connecting terminated with reason: {error,{unknown_target_type,test_name_locator}}
2019-10-02 17:27:04.638 [error] <0.25076.1> CRASH REPORT Process <0.25076.1> with 0 neighbours exited with reason: {error,{unknown_target_type,test_name_locator}} in gen_fsm:terminate/7 line 622
2019-10-02 17:27:04.638 [error] <0.24906.1> Supervisor riak_core_cluster_conn_sup had child {test_name_locator,{"127.0.0.1",4097}} started with riak_core_cluster_conn:start_link({test_name_locator,{"127.0.0.1",4097}}) at <0.25076.1> exit with reason {error,{unknown_target_type,test_name_locator}} in context child_terminated
2019-10-02 17:27:04.638 [error] <0.25077.1> gen_fsm <0.25077.1> in state connecting terminated with reason: {error,{unknown_target_type,test_name_locator}}
2019-10-02 17:27:04.638 [error] <0.25077.1> CRASH REPORT Process <0.25077.1> with 0 neighbours exited with reason: {error,{unknown_target_type,test_name_locator}} in gen_fsm:terminate/7 line 622
2019-10-02 17:27:04.639 [error] <0.24906.1> Supervisor riak_core_cluster_conn_sup had child {test_name_locator,{"127.0.0.1",4097}} started with riak_core_cluster_conn:start_link({test_name_locator,{"127.0.0.1",4097}}) at <0.25077.1> exit with reason {error,{unknown_target_type,test_name_locator}} in context child_terminated
2019-10-02 17:27:04.639 [error] <0.25078.1> gen_fsm <0.25078.1> in state connecting terminated with reason: {error,{unknown_target_type,test_name_locator}}
2019-10-02 17:27:04.639 [error] <0.25078.1> CRASH REPORT Process <0.25078.1> with 0 neighbours exited with reason: {error,{unknown_target_type,test_name_locator}} in gen_fsm:terminate/7 line 622
2019-10-02 17:27:04.639 [error] <0.24906.1> Supervisor riak_core_cluster_conn_sup had child {test_name_locator,{"127.0.0.1",4097}} started with riak_core_cluster_conn:start_link({test_name_locator,{"127.0.0.1",4097}}) at <0.25078.1> exit with reason {error,{unknown_target_type,test_name_locator}} in context child_terminated
2019-10-02 17:27:04.639 [error] <0.24906.1> Supervisor riak_core_cluster_conn_sup had child {test_name_locator,{"127.0.0.1",4097}} started with riak_core_cluster_conn:start_link({test_name_locator,{"127.0.0.1",4097}}) at <0.25078.1> exit with reason reached_max_restart_intensity in context shutdown
